### ISSUE TITLE
Win ShaveDuino contest

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/ArduinoCourse#13]
Peter:

```
Het is toch zo dat ik in de IDE de Arduino Nano moet selecteren?
```

Jeroen: 

```
Als de shaveduino een kristal heeft van 16 MHz dan kun je kiezen voor:
Arduino Pro or Pro mini (5V 16MHz) ATmega 328

En bij 8MHz kiezen voor:
Arduino Pro or Pro mini (3.3V 8MHz) ATmega 328
```

**Comment by richelbilderbeek** [comment]
@thijsvb : How did it work again? I remember something with drivers?

**Comment by thijsvb** [comment]
It didn't show up on the computer as a serial port. The problem wasn't the bootloader, we tried that. I believe that there was also some problem caused because the battery wasn't attached. But a problem with the drivers would make sense too.

**Comment by richelbilderbeek** [comment]
Battery is soldered on, I kept it connected to a laptop for some hours, so I assume it is full.

But those drivers, did we download them somewhere?

**Comment by thijsvb** [comment]
I don't remember where you got the drivers, but I found this on the arduino
forum.
http://forum.arduino.cc/index.php?topic=260897.0

**Comment by richelbilderbeek** [comment]
After 2.9 years, I consider this Issue obsoleted.
