### ISSUE TITLE
Opening Maakplek zaterdag 21 mei

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/ArduinoCourse#49]
Op zaterdag 21 mei heeft de Maakplek (`www.maakplek.nl`) een officiele opening. Wij mogen dan een workshop Arduino geven, van 12:00-13:00. Daarna kan het best zijn dat ze willen dat we blijven: er zijn vast wel meer mensen die ook later mee willen doen! Wie doet er mee?

Op alfabet van nickname:
 - [x] @amaiam 
 - [x] @CoolNeem
 - [x] @jorn600
 - [ ] @ruben-bouman
 - [x] @thijsvb 
 - [ ] @tije1234
 - [x] @XnoemieX 

Natuurlijk hebben we het er vrijdag ook over :-)

**Comment by richelbilderbeek** [comment]
Was gaaf!

**Comment by Bregjearduino** [comment]
Hoi. Was leuk afgelopen zaterdag! 

Wat ik wou vragen heb je nog tickets over voor NEMO? Ik wil wel graag mee als er plek over is. 


Groeten sara






Verzonden met Surface





Van: Richel Bilderbeek
Verzonden: ‎maandag‎ ‎23‎ ‎mei‎ ‎2016 ‎15‎:‎43
Aan: richelbilderbeek/ArduinoCourse





Was gaaf!

**Comment by jorn600** [comment]
NEMO? Wanneer?

Op ma 23 mei 2016 5:53 p.m. schreef Bregjearduino <notifications@github.com

**Comment by Bregjearduino** [comment]
Hoi die was voor Richel bedoeld. 1 juli NEMO Amsterdam. Zal m doorsturen.


groeten






Verzonden met Surface





Van: jorn600
Verzonden: ‎maandag‎ ‎23‎ ‎mei‎ ‎2016 ‎17‎:‎55
Aan: richelbilderbeek/ArduinoCourse
CC: sara b, Comment




NEMO? Wanneer?

Op ma 23 mei 2016 5:53 p.m. schreef Bregjearduino <notifications@github.com

**Comment by jorn600** [comment]
Op een vrijdag tijdens de presentaties?

Op ma 23 mei 2016 5:58 p.m. schreef Bregjearduino <notifications@github.com

**Comment by Bregjearduino** [comment]
Vergissing.  zaterdag 2 juli vlgs mij.









Verzonden met Surface





Van: jorn600
Verzonden: ‎maandag‎ ‎23‎ ‎mei‎ ‎2016 ‎18‎:‎05
Aan: richelbilderbeek/ArduinoCourse
CC: sara b, Comment




Op een vrijdag tijdens de presentaties?

Op ma 23 mei 2016 5:58 p.m. schreef Bregjearduino <notifications@github.com

**Comment by jorn600** [comment]
Ik wil wel als je nog kaarten hebt

Op ma 23 mei 2016 6:32 p.m. schreef Bregjearduino <notifications@github.com

**Comment by richelbilderbeek** [comment]
@jorn600 en @Bregjearduino : dan zo snel mogelijk mailen naar `info apestaartje dejongeonderzoekers punt nl`, aangezien de deadline rond vandaag is.

**Comment by jorn600** [comment]
Sara heb je al tickets? Ik ben er nu mee bezig.

Op di 24 mei 2016 8:58 a.m. schreef Richel Bilderbeek <
notifications@github.com>:

**Comment by Bregjearduino** [comment]
hee Jorn, ik heb net mail gestuurd naar info@jongeonderzoekers.nl voor 2 tickets,  . ook voor jou gevraagd . mgl. moet het nu goedkomen. misschien heb je het al rond weet ik dus nog niet.
groeten sara

Date: Tue, 24 May 2016 01:17:00 -0700

**Comment by jorn600** [comment]
We kunnen ook wel samen heen?  En over de tickets weet ik het precies nog
niet.

Op di 24 mei 2016 10:38 a.m. schreef Bregjearduino <notifications@github.com

**Comment by dpstruwe** [comment]
Hallo Sara / Jorn, om welke tickets gaat het? is dat voor Nemo?

Peter

**Comment by Bregjearduino** [comment]
Ja, Richel had afgelopen zaterdag vermeld dat kinderen zich konden opgeven voor NEMO. Maar eerlijk lijk gezegd had ik niet helemaal goed opgelet hoe en wat. Blijkbaar gaat het via de jonge onderzoekers zelf ofzo. dus heb net mail gestuurd naar djo zelf.

Date: Tue, 24 May 2016 02:07:44 -0700

**Comment by Bregjearduino** [comment]
dat is ok. met de trein.

Date: Tue, 24 May 2016 02:00:26 -0700

**Comment by jorn600** [comment]
Ja.

Op di 24 mei 2016 11:07 a.m. schreef dpstruwe <notifications@github.com>:

**Comment by jorn600** [comment]
Ik heb nu een kaartje. We kunnen wel samen heen Sara?

Op di 24 mei 2016 11:12 a.m. schreef jorn prenger <jorn.prenger@gmail.com>:

**Comment by jorn600** [comment]
Of ga je met je zoon/dochter?

**Comment by Bregjearduino** [comment]
Heb nog geen bericht. Maar anders koop ik wel een kaartje.


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: jorn600 <notifications@github.com>
Datum: 24-05-2016  11:37  (GMT+01:00)
Aan: richelbilderbeek/ArduinoCourse <ArduinoCourse@noreply.github.com>
Cc: Bregjearduino <oegemasara@hotmail.com>, Mention <mention@noreply.github.com>
Onderwerp: Re: [richelbilderbeek/ArduinoCourse] Opening Maakplek zaterdag 21 mei (#49)

Of ga je met je zoon/dochter?


---

**Comment by jorn600** [comment]
Ik denk omdat je volwassen benr

Op di 24 mei 2016 11:48 a.m. schreef Bregjearduino <notifications@github.com

**Comment by jorn600** [comment]
Je kunt wel met mij mee als begeleider

Op di 24 mei 2016 12:34 p.m. schreef jorn prenger <jorn.prenger@gmail.com>:

**Comment by richelbilderbeek** [comment]
Gezellig, zo'n openbaar gesprek op de GitHub :smile:

**Comment by jorn600** [comment]
Ja je!😃

Op di 24 mei 2016 1:34 p.m. schreef Richel Bilderbeek <
notifications@github.com>:
