### ISSUE TITLE
Minecraft en Arduino

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/ArduinoCourse#50]
[Hier staat hoe het moet](https://mcreator.pylo.co/arduino)

**Comment by dpstruwe** [comment]
Leuk!

Snap echte niets van de code, is dat een uitbreiding van de Arduino taal? Of allerlei functie uit een library die je aanroept?

Groet,

Peter

**Comment by richelbilderbeek** [comment]
> Snap echte niets van de code, is dat een uitbreiding van de Arduino taal? 
> Of allerlei functie uit een library die je aanroept? 
Het zijn allerlei functie uit een library die je aanroept. Ik heb het nog niet werken gekregen, i.v.m. promotie.

**Comment by richelbilderbeek** [comment]
Misschien leuk voor @CoolNeem ?

**Comment by richelbilderbeek** [comment]
Obsoleted.
