### ISSUE TITLE
Project van directeur: vrijdag 19:30

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/ArduinoCourse#54]
Vrijdag 28 oktober 19:30 komt Carleen, de directeur van DJO, langs voor een project. Zij zoekt leerlingen die dit willen bouwen. DJO zal de onderdelen voor dit project betalen. De leerlingen mogen natuurlijk nee zeggen tegen het project.

Ik denk zelf aan @jorn600 , @thijsvb , @XnoemieX , @amaiam , maar dit kunnen er best meer zijn.

Om 19:30 komt ze langs, dan kunnen de geinteresseerden apart met haar zitten.

**Comment by thijsvb** [comment]
Mee bezig, zie [deze repository](http://github.com/thijsvb/DJO-Registrator)
