### ISSUE TITLE
Amiibo clones maken met Arduino en RFID lezer

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/ArduinoCourse#63]
https://games.kel.mn/en/create-amiibo-clones-with-arduino/

**Comment by jorn600** [comment]
Lijkt me gaaf! wanneer?

**Comment by richelbilderbeek** [comment]
Geen idee, ik heb amper een idee wat Amiibo's zijn. Spreek ik je volgende week hierover: jij hebt er meer verstand van dan ik :+1:

**Comment by richelbilderbeek** [comment]
Apparently, out RFID reader cannot read Amiibo's. Too bad...
